logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: DEBUG
    com.fmd.api_gateway: ERROR
    org.hibernate.SQL: ERROR
  pattern:
    console: "%highlight([%-5level]) %logger{36} - %msg%n"
  file:
    name: C:/log/api-gateway/log.json
  logback:
    rollingpolicy:
      max-history: 10
      max-file-size: 10MB
      total-size-cap: 100MB
  structured:
    format:
      file: ecs
    ecs:
      service:
        name: api-gateway
        version: 1.0.0
        environment: dev
        node-name: Primary

