spring:
  application:
    name: api-gateway
  config:
    import: classpath:application-logging.yaml
  cloud:
    gateway:
      routes:
        - id: security-service
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/auth-service/**
        - id: spring-jpa-demo
          uri: lb://SPRING-JPA-DEMO
          predicates:
            - Path=/spring-jpa-demo/**

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true


