# Spring Boot application configuration file
spring:
  application:
    name: SPRING-JPA-DEMO
  config:
    import: classpath:application-logging.yaml

server:
  servlet:
    context-path: /spring-jpa-demo

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

request:
  body:
    sanitization:
      enabled: true
  header:
    validation:
      enabled: true
      fields: Authorization
    logging:
      enabled: false
      fields: X-Request-ID, X-Correlation-ID