logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    org.springframework.security: ERROR
    com.fmd.spring_jpa_demo: TRACE
    org.hibernate.SQL: ERROR
  pattern:
    console: "%highlight([%-5level]) %logger{36} - %msg%n"
  file:
    name: C:/log/spring-jpa-demo/log.json
  logback:
    rollingpolicy:
      max-history: 10
      max-file-size: 10MB
      total-size-cap: 100MB
  structured:
    format:
      file: ecs
    ecs:
      service:
        name: spring-jpa-demo
        version: 1.0.0
        environment: dev
        node-name: Primary

