apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spring-jpa-demo.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ include "spring-jpa-demo.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "spring-jpa-demo.name" . }}
    spec:
      containers:
        - name: {{ include "spring-jpa-demo.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
            - containerPort: {{ .Values.service.actuatorPort }}
          envFrom:
            - configMapRef:
                name: {{ include "spring-jpa-demo.fullname" . }}-env
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.service.actuatorPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.service.actuatorPort }}
            initialDelaySeconds: 10
            periodSeconds: 10

