apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-registry.fullname" . }}-actuator
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.actuatorPort }}
      targetPort: {{ .Values.service.actuatorPort }}
      protocol: TCP
      name: actuator
  selector:
    app: {{ include "service-registry.name" . }}
